# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_codelist_wrappers", use_symbols = TRUE, package_name = "codelist")

#' @usage NULL
#' @useDynLib codelist, .registration = TRUE
NULL

hello <- function() .Call(wrap__hello)

Codelist <- new.env(parent = emptyenv())

Codelist$new <- function(name) .Call(wrap__Codelist__new, name)

Codelist$set_name <- function(new_name) .Call(wrap__Codelist__set_name, self, new_name)

Codelist$get_entries <- function() .Call(wrap__Codelist__get_entries, self)

#' @export
`$.Codelist` <- function (self, name) { func <- Codelist[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Codelist` <- `$.Codelist`


# nolint end
