# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_codelist_wrappers", use_symbols = TRUE, package_name = "codelist")

#' @usage NULL
#' @useDynLib codelist, .registration = TRUE
NULL

hello <- function() .Call(wrap__hello)


# nolint end
