name: Run Preflight Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Rust Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Rust components
        working-directory: rust
        run: rustup component add clippy rustfmt

      - name: Set R_HOME env var
        run: echo "R_HOME=$(R RHOME)" >> $GITHUB_ENV

      - name: Format check
        working-directory: rust
        run: cargo fmt --all -- --check

      - name: Clippy check
        working-directory: rust
        run: cargo clippy --all-targets --all-features -- -D warnings
